resolver: lts-6.35

packages:
- '.'

#- ../top-apps

- location:
     git: https://github.com/Quid2/top-apps
     commit: 15931bf36d5aeba24e9b1b77eff91e51e8c972a1
  extra-dep: true

extra-deps:
- model-0.4.2
- flat-0.3
- zm-0.3
- top-0.2.2
- x86-64bit-0.4.5
- cryptonite-0.22
- smtps-gmail-1.3.2
- acid-state-0.14.3
- ed25519-0.0.5.0
- mono-traversable-1.0.4.0
