resolver: lts-7.23

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../model
# - ../flat
# - ../zm
#- ../top
- ../top-apps

# - location:
#     git: https://github.com/divipp/x86-64
#     commit: 5f53cf0d426f6a8fde9a66a53b1aabdb9bcd6cda
#     # extra-deps: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- model-0.3
- flat-0.3
- zm-0.2.4
- top-0.2
#- hslogger-1.2.9
- x86-64bit-0.4.5
- ed25519-0.0.5.0
- cryptonite-0.22
