resolver: lts-6.22
#resolver: lts-7.4

# Local packages, usually specified by relative directory name
packages:
- '.'
#- ../model
#- ../flat
#- ../typed
# - ../top

- location:
    git: https://github.com/tittoassini/top
    commit: 7509f2fd89204b23cc0039e7484860487ca3a160
  extra-dep: true
- location:
    git: https://github.com/tittoassini/typed
    commit: 00b39b1e94dc2a047e6371a1622c8ee411882efe
  extra-dep: true
- location:
   git: https://github.com/tittoassini/flat
   commit: 3771f5946dd506c6f199aa4047186d5b57bdce5f
  extra-dep: true
- location:
   git: https://github.com/tittoassini/model
   commit: b05a56a993213271e3b13d28a5e8bb90c9d8576f
  extra-dep: true

- location:
    git: https://github.com/divipp/x86-64
    commit: 5f53cf0d426f6a8fde9a66a53b1aabdb9bcd6cda
  # extra-deps: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- hslogger-1.2.9
# - x86-64bit-0.4.4

# - plugins-1.5.5.0
# - ed25519-0.0.5.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
